# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# This program will connect the website www.traintogrow.net from the Yodataylor/TraintoGrowP repository and attach it to a target web app in
# Azure Web App Services in the name of TRAINTOGROW. TRAINTOGROW was created in Web App Services and is used as the final point for the site to be
# hosted, being published on the World Wide Web.  This was done by Brian E Taylor. The project started in June 2022.  Changes can now be made from 
# the Ionos Platform, which was chosen by the client/customer, and also in Github with the support of VScode on a local server.  
name: Build and deploy PHP app to Azure Web App - TRAINTOGROW

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'TRAINTOGROW'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB56F3C04BF14E4BA65954DABA7E2AC4 }}
          package: .
